Repository Adyen/adyen-php-api-library, pull requests merged in 2023-04, with the labels that each got.

#477 [ITT-411] POSTerminalManagement endpoints
  sonar-project.properties
  src/Adyen/Model/POSTerminalManagement/Address.php
  src/Adyen/Model/POSTerminalManagement/AssignTerminalsRequest.php
  src/Adyen/Model/POSTerminalManagement/AssignTerminalsResponse.php
  src/Adyen/Model/POSTerminalManagement/FindTerminalRequest.php
  src/Adyen/Model/POSTerminalManagement/FindTerminalResponse.php
  src/Adyen/Model/POSTerminalManagement/GetStoresUnderAccountRequest.php
  src/Adyen/Model/POSTerminalManagement/GetStoresUnderAccountResponse.php
  src/Adyen/Model/POSTerminalManagement/GetTerminalDetailsRequest.php
  src/Adyen/Model/POSTerminalManagement/GetTerminalDetailsResponse.php
  src/Adyen/Model/POSTerminalManagement/GetTerminalsUnderAccountRequest.php
  src/Adyen/Model/POSTerminalManagement/GetTerminalsUnderAccountResponse.php
  src/Adyen/Model/POSTerminalManagement/MerchantAccount.php
  src/Adyen/Model/POSTerminalManagement/ModelInterface.php
  src/Adyen/Model/POSTerminalManagement/ObjectSerializer.php
  src/Adyen/Model/POSTerminalManagement/ServiceError.php
  src/Adyen/Model/POSTerminalManagement/Store.php
  src/Adyen/Service/POSTerminalManagementApi.php
  tests/Resources/POSManagement/assign-terminals.json
  tests/Resources/POSManagement/terminals-under-account.json
  tests/Unit/POSTerminalTest.php
Labels: Feature

#480 [ITT-413] Data Protection API
  Makefile
  README.md
  phpcs.xml
  sonar-project.properties
  src/Adyen/Model/DataProtection/ModelInterface.php
  src/Adyen/Model/DataProtection/ObjectSerializer.php
  src/Adyen/Model/DataProtection/ServiceError.php
  src/Adyen/Model/DataProtection/SubjectErasureByPspReferenceRequest.php
  src/Adyen/Model/DataProtection/SubjectErasureResponse.php
  src/Adyen/Service/DataProtectionApi.php
  templates/partial_header.mustache
  tests/Resources/DataProtection/authorization-error.json
  tests/Resources/DataProtection/post-request-subject-erasure-success.json
  tests/Unit/DataProtectionTest.php
  tests/Unit/TestCaseMock.php
Labels: Feature

#475 [ITT-409] Payouts API
  sonar-project.properties
  src/Adyen/Model/Payout/Address.php
  src/Adyen/Model/Payout/Amount.php
  src/Adyen/Model/Payout/BankAccount.php
  src/Adyen/Model/Payout/Card.php
  src/Adyen/Model/Payout/FraudCheckResult.php
  src/Adyen/Model/Payout/FraudResult.php
  src/Adyen/Model/Payout/FundSource.php
  src/Adyen/Model/Payout/ModelInterface.php
  src/Adyen/Model/Payout/ModifyRequest.php
  src/Adyen/Model/Payout/ModifyResponse.php
  src/Adyen/Model/Payout/Name.php
  src/Adyen/Model/Payout/ObjectSerializer.php
  src/Adyen/Model/Payout/PayoutRequest.php
  src/Adyen/Model/Payout/PayoutResponse.php
  src/Adyen/Model/Payout/Recurring.php
  src/Adyen/Model/Payout/ResponseAdditionalData3DSecure.php
  src/Adyen/Model/Payout/ResponseAdditionalDataBillingAddress.php
  src/Adyen/Model/Payout/ResponseAdditionalDataCard.php
  src/Adyen/Model/Payout/ResponseAdditionalDataCommon.php
  src/Adyen/Model/Payout/ResponseAdditionalDataInstallments.php
  src/Adyen/Model/Payout/ResponseAdditionalDataNetworkTokens.php
  src/Adyen/Model/Payout/ResponseAdditionalDataOpi.php
  src/Adyen/Model/Payout/ResponseAdditionalDataSepa.php
  src/Adyen/Model/Payout/ServiceError.php
  src/Adyen/Model/Payout/StoreDetailAndSubmitRequest.php
  src/Adyen/Model/Payout/StoreDetailAndSubmitResponse.php
  src/Adyen/Model/Payout/StoreDetailRequest.php
  src/Adyen/Model/Payout/StoreDetailResponse.php
  src/Adyen/Model/Payout/SubmitRequest.php
  src/Adyen/Model/Payout/SubmitResponse.php
  src/Adyen/Service/Payout/InitializationApi.php
  src/Adyen/Service/Payout/InstantPayoutsApi.php
  src/Adyen/Service/Payout/ReviewingApi.php
  tests/Resources/Payouts/confirm-third-party.json
  tests/Resources/Payouts/instant-payout.json
  tests/Resources/Payouts/store-detail.json
  tests/Unit/ModelBasedPayoutTest.php
Labels: Feature

#474 [ITT-408] Generate Recurring API
  src/Adyen/Model/Recurring/Address.php
  src/Adyen/Model/Recurring/Amount.php
  src/Adyen/Model/Recurring/BankAccount.php
  src/Adyen/Model/Recurring/Card.php
  src/Adyen/Model/Recurring/CreatePermitRequest.php
  src/Adyen/Model/Recurring/CreatePermitResult.php
  src/Adyen/Model/Recurring/DisablePermitRequest.php
  src/Adyen/Model/Recurring/DisablePermitResult.php
  src/Adyen/Model/Recurring/DisableRequest.php
  src/Adyen/Model/Recurring/DisableResult.php
  src/Adyen/Model/Recurring/ModelInterface.php
  src/Adyen/Model/Recurring/Name.php
  src/Adyen/Model/Recurring/NotifyShopperRequest.php
  src/Adyen/Model/Recurring/NotifyShopperResult.php
  src/Adyen/Model/Recurring/ObjectSerializer.php
  src/Adyen/Model/Recurring/Permit.php
  src/Adyen/Model/Recurring/PermitRestriction.php
  src/Adyen/Model/Recurring/PermitResult.php
  src/Adyen/Model/Recurring/Recurring.php
  src/Adyen/Model/Recurring/RecurringDetail.php
  src/Adyen/Model/Recurring/RecurringDetailsRequest.php
  src/Adyen/Model/Recurring/RecurringDetailsResult.php
  src/Adyen/Model/Recurring/ScheduleAccountUpdaterRequest.php
  src/Adyen/Model/Recurring/ScheduleAccountUpdaterResult.php
  src/Adyen/Model/Recurring/ServiceError.php
  src/Adyen/Model/Recurring/TokenDetails.php
  src/Adyen/Service/RecurringApi.php
  tests/Unit/ModelBasedRecurringTest.php
Labels: Feature

#478 [ITT-412] StoredValue API
  src/Adyen/Model/StoredValue/Amount.php
  src/Adyen/Model/StoredValue/ModelInterface.php
  src/Adyen/Model/StoredValue/ObjectSerializer.php
  src/Adyen/Model/StoredValue/ServiceError.php
  src/Adyen/Model/StoredValue/StoredValueBalanceCheckRequest.php
  src/Adyen/Model/StoredValue/StoredValueBalanceCheckResponse.php
  src/Adyen/Model/StoredValue/StoredValueBalanceMergeRequest.php
  src/Adyen/Model/StoredValue/StoredValueBalanceMergeResponse.php
  src/Adyen/Model/StoredValue/StoredValueIssueRequest.php
  src/Adyen/Model/StoredValue/StoredValueIssueResponse.php
  src/Adyen/Model/StoredValue/StoredValueLoadRequest.php
  src/Adyen/Model/StoredValue/StoredValueLoadResponse.php
  src/Adyen/Model/StoredValue/StoredValueStatusChangeRequest.php
  src/Adyen/Model/StoredValue/StoredValueStatusChangeResponse.php
  src/Adyen/Model/StoredValue/StoredValueVoidRequest.php
  src/Adyen/Model/StoredValue/StoredValueVoidResponse.php
  src/Adyen/Service/StoredValueApi.php
  tests/Resources/StoredValue/change-status.json
  tests/Resources/StoredValue/void-transaction.json
  tests/Unit/StoredValueTest.php
Labels: Feature

#472 [ITT-404] Transfers Endpoints
  src/Adyen/Model/Transfers/AULocalAccountIdentification.php
  src/Adyen/Model/Transfers/AdditionalBankIdentification.php
  src/Adyen/Model/Transfers/Address2.php
  src/Adyen/Model/Transfers/Amount.php
  src/Adyen/Model/Transfers/BRLocalAccountIdentification.php
  src/Adyen/Model/Transfers/BankAccountV3.php
  src/Adyen/Model/Transfers/BankAccountV3AccountIdentification.php
  src/Adyen/Model/Transfers/CALocalAccountIdentification.php
  src/Adyen/Model/Transfers/CZLocalAccountIdentification.php
  src/Adyen/Model/Transfers/CounterpartyInfoV3.php
  src/Adyen/Model/Transfers/CounterpartyV3.php
  src/Adyen/Model/Transfers/DKLocalAccountIdentification.php
  src/Adyen/Model/Transfers/HULocalAccountIdentification.php
  src/Adyen/Model/Transfers/IbanAccountIdentification.php
  src/Adyen/Model/Transfers/InvalidField.php
  src/Adyen/Model/Transfers/JSONObject.php
  src/Adyen/Model/Transfers/JSONPath.php
  src/Adyen/Model/Transfers/Link.php
  src/Adyen/Model/Transfers/Links.php
  src/Adyen/Model/Transfers/MerchantData.php
  src/Adyen/Model/Transfers/ModelInterface.php
  src/Adyen/Model/Transfers/NOLocalAccountIdentification.php
  src/Adyen/Model/Transfers/NameLocation.php
  src/Adyen/Model/Transfers/NumberAndBicAccountIdentification.php
  src/Adyen/Model/Transfers/ObjectSerializer.php
  src/Adyen/Model/Transfers/PLLocalAccountIdentification.php
  src/Adyen/Model/Transfers/PartyIdentification2.php
  src/Adyen/Model/Transfers/RestServiceError.php
  src/Adyen/Model/Transfers/SELocalAccountIdentification.php
  src/Adyen/Model/Transfers/SGLocalAccountIdentification.php
  src/Adyen/Model/Transfers/Transaction.php
  src/Adyen/Model/Transfers/TransactionSearchResponse.php
  src/Adyen/Model/Transfers/Transfer.php
  src/Adyen/Model/Transfers/TransferInfo.php
  src/Adyen/Model/Transfers/UKLocalAccountIdentification.php
  src/Adyen/Model/Transfers/USLocalAccountIdentification.php
  src/Adyen/Service.php
  src/Adyen/Service/Transfers/TransactionsApi.php
  src/Adyen/Service/Transfers/TransfersApi.php
  tests/Resources/Tranfers/all-transactions-get.json
  tests/Resources/Tranfers/transfer-funds.json
  tests/Unit/TransfersTest.php
Labels: Feature

#476 [ITT-410] BinLookup API
  src/Adyen/Model/BinLookup/Amount.php
  src/Adyen/Model/BinLookup/BinDetail.php
  src/Adyen/Model/BinLookup/CardBin.php
  src/Adyen/Model/BinLookup/CostEstimateAssumptions.php
  src/Adyen/Model/BinLookup/CostEstimateRequest.php
  src/Adyen/Model/BinLookup/CostEstimateResponse.php
  src/Adyen/Model/BinLookup/DSPublicKeyDetail.php
  src/Adyen/Model/BinLookup/MerchantDetails.php
  src/Adyen/Model/BinLookup/ModelInterface.php
  src/Adyen/Model/BinLookup/ObjectSerializer.php
  src/Adyen/Model/BinLookup/Recurring.php
  src/Adyen/Model/BinLookup/ServiceError.php
  src/Adyen/Model/BinLookup/ThreeDS2CardRangeDetail.php
  src/Adyen/Model/BinLookup/ThreeDSAvailabilityRequest.php
  src/Adyen/Model/BinLookup/ThreeDSAvailabilityResponse.php
  src/Adyen/Service/BinLookupApi.php
  tests/Resources/BinLookup/3ds-availability.json
  tests/Unit/BinLookupTest.php
Labels: Feature

#492 Deprecate old services
  src/Adyen/Service/BinLookup.php
  src/Adyen/Service/Checkout.php
  src/Adyen/Service/CheckoutUtility.php
  src/Adyen/Service/Management.php
  src/Adyen/Service/Modification.php
  src/Adyen/Service/Payment.php
  src/Adyen/Service/Payout.php
  src/Adyen/Service/Recurring.php
Labels: Feature

#464 CurlClient request fix
  src/Adyen/HttpClient/CurlClient.php
Labels: bug

#491 Create release.yml
  .github/release.yml
Labels: Feature

#485 [ITT-477] Adjust README in preparation of release
  README.md
Labels: Feature

#484 rename notificationReceiver to webhookReceiver
  src/Adyen/Service/NotificationReceiver.php
  src/Adyen/Service/WebhookReceiver.php
Labels: breaking change
